<?php

return [
    'SHOPEE_PATNER_ID' => env('SHOPEE_PATNER_ID'),
    'SHOPEE_PATNER_KEY' => env('SHOPEE_PATNER_KEY'),
    'SHOPEE_REDIRECT_URL' => env('SHOPEE_REDIRECT_URL'),
    'SHOPEE_PRODUCTION_STATUS' => env('SHOPEE_PRODUCTION_STATUS'),
];